version: "3"
services:
  mysql:
    container_name: mysqllocal
    # command: --default-authentication-plugin=mysql_native_password
    image: mysqllocal
    restart: always
    ports:
      - 3306:3306
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_DATABASE: tezos
    networks:
      - app-network
  app:
    container_name: applocal
    image: javonheng/tezostestlocal
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./:/home/node/app
    networks:
      - app-network
    depends_on:
      - "mysql"
    command: ["./wait-for-it.sh", "npm", "run", "dev"]
networks:
  app-network:
    driver: bridge
